# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
xcode_sdk: iphonesimulator12.0
language: swift

before_install:
  # Fix Travis  xcodebuild exited with 65 https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone XS (12.0" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
  
# cache: cocoapods
# podfile: Example/Podfile
before_install:
# - gem install cocoapods --pre # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:

- set -o pipefail && xcodebuild -workspace 'Example/ASPVideoPlayer.xcworkspace' -scheme 'ASPVideoPlayer-Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.0,name=iPhone XS' build test | xcpretty -c
- pod lib lint --allow-warnings

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'ASPVideoPlayer'
